Repository FieldTripper/FE-FieldTripper, pull requests merged in 2022-12, with the labels that each got.

#14 Feat/museum container side list
  package-lock.json
  src/components/MuseumCard/MuseumCard.css
  src/components/MuseumCard/MuseumCard.js
  src/components/MuseumsContainer/MuseumsContainer.css
  src/components/MuseumsContainer/MuseumsContainer.js
  src/index.js
Labels: enhancement

#18 Feature/header
  package.json
  public/index.html
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MuseumCard/MuseumCard.css
  src/components/MuseumCard/MuseumCard.js
  src/components/SearchForm/SearchForm.css
  src/components/SearchForm/SearchForm.js
  src/images/bus.png
  src/images/city.png
  src/images/logo.png
Labels: enhancement

#19 Feat/mockdata config
  src/components/Header/Header.css
  src/components/MuseumCard/MuseumCard.js
  src/components/MuseumsContainer/MuseumsContainer.js
  src/components/SearchForm/SearchForm.css
  src/index.js
Labels: enhancement

#20 Feature/footer
  src/components/App/App.css
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/SearchForm/SearchForm.css
  src/components/SearchForm/SearchForm.js
  src/images/text-only.png
Labels: enhancement

#23 Feat/booking form
  src/components/App/App.js
  src/components/BookingForm/BookingForm.css
  src/components/BookingForm/BookingForm.js
  src/components/MuseumsContainer/MuseumsContainer.js
Labels: enhancement

#35 Feat/map rendering locations
  src/components/BookingForm/BookingForm.js
  src/components/SearchForm/SearchForm.js
  src/testData/museumsData.js
  src/testData/singleMuseumData.js
Labels: documentation

#37 Feature/trip type
  src/components/About/About.css
  src/components/About/About.js
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MuseumCard/MuseumCard.css
  src/components/MuseumCard/MuseumCard.js
  src/components/MuseumsContainer/MuseumsContainer.css
  src/components/MuseumsContainer/MuseumsContainer.js
  src/components/SearchForm/SearchForm.css
  src/components/TripType/TripType.css
  src/components/TripType/TripType.js
Labels: enhancement

#38 Feat/map rendering locations
  package-lock.json
  package.json
  src/components/BookingForm/BookingForm.css
  src/components/BookingForm/BookingForm.js
  src/components/LocationPin/LocationPin.css
  src/components/LocationPin/LocationPin.jsx
  src/components/Map/Map.css
  src/components/Map/Map.js
  src/components/Map/Map.jsx
  src/components/Marker/Marker.js
  src/components/MuseumCard/MuseumCard.js
  src/components/MuseumsContainer/MuseumsContainer.js
  src/images/location-pin.png
Labels: enhancement

#41 Feature/host configuration
  package-lock.json
  src/components/App/App.js
  src/components/ExistingTrips/ExistingTrips.css
  src/components/ExistingTrips/ExistingTrips.js
  src/components/MuseumInfo/MuseumInfo.css
  src/components/MuseumInfo/MuseumInfo.js
  src/components/TripType/TripType.js
Labels: enhancement

#45 Feature/museum info
  src/components/Footer/Footer.css
  src/components/MuseumInfo/MuseumInfo.css
  src/components/MuseumInfo/MuseumInfo.js
Labels: enhancement

#47 Add two values to dropdown
  src/components/App/App.js
  src/components/BookingForm/BookingForm.js
Labels: bug

#54 Cypress
  cypress/e2e/booking-form.cy.js
  cypress/e2e/landing-page.cy.js
  cypress/e2e/museumInfo.cy.js
  cypress/e2e/museums.cy.js
  cypress/e2e/search-form.cy.js
  cypress/e2e/trip-type.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/museum.json
  cypress/fixtures/museumData.json
  cypress/fixtures/museumInfo.json
  package-lock.json
  package.json
  src/components/About/About.css
  src/components/App/App.css
  src/components/BookingForm/BookingForm.css
  src/components/BookingForm/BookingForm.js
  src/components/ExistingTrips/ExistingTrips.css
  src/components/ExistingTrips/ExistingTrips.js
  src/components/Footer/Footer.css
  src/components/LoginForm/LoginForm.css
  src/components/LoginForm/LoginForm.js
  src/components/Map/Map.css
  src/components/Map/Map.jsx
  src/components/MuseumCard/MuseumCard.css
  src/components/MuseumCard/MuseumCard.js
  src/components/MuseumInfo/MuseumInfo.css
  src/components/MuseumsContainer/MuseumsContainer.css
  src/components/SearchForm/SearchForm.css
  src/components/TripType/TripType.css
  src/components/TripType/TripType.js
Labels: enhancement, help wanted

#56 Add id to trip
  src/components/BookingForm/BookingForm.js
  src/queries/queries.js
Labels: bug

#59 Refactor AddTrip Mutation
  src/components/BookingForm/BookingForm.js
  src/components/MuseumsContainer/MuseumsContainer.js
  src/components/UserSavedTripCard/UserSavedTripCard.js
  src/components/UserSavedTrips/UserSavedTrips.js
  src/queries/queries.js
Labels: bug

#60 Feat/add all trip details
  src/components/BookingForm/BookingForm.js
  src/components/TripType/TripType.js
  src/components/UserSavedTripCard/UserSavedTripCard.js
  src/components/UserSavedTrips/UserSavedTrips.js
  src/queries/queries.js
Labels: enhancement

#63 Add render to join trip
  src/components/App/App.js
  src/components/MuseumCard/MuseumCard.css
  src/components/MuseumCard/MuseumCard.js
  src/components/MuseumInfo/MuseumInfo.js
  src/components/MuseumsContainer/MuseumsContainer.js
  src/components/TripCard/TripCard.js
  src/components/TripType/TripType.css
  src/components/TripType/TripType.js
  src/components/UserSavedTripCard/UserSavedTripCard.js
  src/queries/queries.js
Labels: enhancement

#64 Feature/saved trips
  src/components/ExistingTrips/ExistingTrips.css
  src/components/ExistingTrips/ExistingTrips.js
  src/components/MuseumInfo/MuseumInfo.css
  src/components/UserSavedTripCard/UserSavedTripCard.css
  src/components/UserSavedTripCard/UserSavedTripCard.js
  src/components/UserSavedTrips/UserSavedTrips.css
  src/components/UserSavedTrips/UserSavedTrips.js
Labels: enhancement

#67 Feat/filter trips
  src/components/App/App.js
  src/components/ExistingTrips/ExistingTrips.css
  src/components/ExistingTrips/ExistingTrips.js
  src/components/TripCard/TripCard.css
  src/components/TripCard/TripCard.js
  src/components/TripType/TripType.js
  src/components/UserSavedTripCard/UserSavedTripCard.js
  src/components/UserSavedTrips/UserSavedTrips.js
  src/queries/queries.js
Labels: enhancement

#68 Filter by Id from BE
  src/components/BookingForm/BookingForm.js
  src/components/MuseumCard/MuseumCard.js
  src/components/TripType/TripType.js
  src/components/UserSavedTrips/UserSavedTrips.js
  src/queries/queries.js
Labels: enhancement

#71 Feat/about page
  src/components/About/About.css
  src/components/About/About.js
  src/images/GitHub-Logo.svg
  src/images/LinkedIn-Logo.svg
Labels: enhancement

#77 Bug/saved component
  src/components/About/About.css
  src/components/About/About.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/BaseForm/BaseForm.css
  src/components/BookingForm/BookingForm.css
  src/components/BookingForm/BookingForm.js
  src/components/ExistingTrips/ExistingTrips.css
  src/components/Header/Header.css
  src/components/LocationPin/LocationPin.css
  src/components/Map/Map.css
  src/components/MuseumInfo/MuseumInfo.css
  src/components/MuseumInfo/MuseumInfo.js
  src/components/MuseumsContainer/MuseumsContainer.css
  src/components/SearchForm/SearchForm.css
  src/components/SearchForm/SearchForm.js
  src/components/SignUpForm/SignUpForm.css
  src/components/SignUpForm/SignUpForm.js
  src/components/TripCard/TripCard.css
  src/components/TripType/TripType.css
  src/components/UserSavedTripCard/UserSavedTripCard.css
  src/components/UserSavedTrips/UserSavedTrips.css
Labels: bug

#101 Update styling and colors for lighthouse audits
  src/components/About/About.css
  src/components/About/About.js
  src/components/BookingForm/BookingForm.css
  src/components/BookingForm/BookingForm.js
  src/components/MuseumCard/MuseumCard.js
  src/components/TripCard/TripCard.css
  src/components/UserSavedTripCard/UserSavedTripCard.css
  src/components/UserSavedTrips/UserSavedTrips.css
Labels: enhancement

#102 Refactor/add home
  src/components/BookingForm/BookingForm.js
  src/components/ExistingTrips/ExistingTrips.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/SignOut/SignOut.css
  src/components/UserSavedTripCard/UserSavedTripCard.js
  src/queries/queries.js
  src/utilities/utilities.js
Labels: enhancement

#103 Clean up base form
  src/components/BaseForm/BaseForm.js
Labels: enhancement
